### ISSUE TITLE
MessageNotUnderstood: LiteralNode>>selector from PPParser (Parser) >> #messagePart:repeat:

### ISSUE THREAD

**Issue by LinqLover** [tom95/poppy-print#11]
Occurs when poppy-printing this beautiful method: https://github.com/LinqLover/SimulationStudio/blob/cad846fdee882e676d5e97ccfb5fad32336d4a6d/packages/SimulationStudio-Sandbox.package/SandboxContext.class/instance/doPrimitive.method.receiver.args..st

(Please let me know if you can reproduce this because my image contains a modified inlining implementation of `#caseOf:` - not sure whether I sent it to squeak-dev at any time.)

**Comment by tom95** [comment]
Thanks for this example :D 

After fixing the bug you reported I stumbled upon the issue that our hack for inserting empty lines breaks with caseOf's transform. A proper fix would be to turn off transforms all together for our purposes, for now I settled for a hack.

The method still doesn't look great but that's mostly due to the comments being wrapped to new lines, which I would say is best described in this issue: https://github.com/tom95/poppy-print/issues/8
