### ISSUE TITLE
Comments are mixed up when using the pretty printer

### ISSUE THREAD

**Issue by LinqLover** [tom95/poppy-print#4]
Take a look at the pretty-printed version of `HandMorph>>handleEvent:`. The same comment appears again and again!

**Comment by tom95** [comment]
Should be fixed now. The reason was quite interesting, too: the Parser will ask its Encoder when encountering literals and variables if these are already known and in that case reuse the existing instances. This is obviously undesirable when we associate comments with specific positions rather than instances of literals or variables.
